{"repo": "home-assistant/core", "pull_number": 136998, "instance_id": "home-assistant__core-136998", "issue_numbers": ["136988", "136988"], "base_commit": "c7041a97be79def58ffc771e2e3b2702f4c8b9cd", "patch": "diff --git a/homeassistant/components/swiss_public_transport/strings.json b/homeassistant/components/swiss_public_transport/strings.json\nindex 270cb097e0a3a..64817f89f426e 100644\n--- a/homeassistant/components/swiss_public_transport/strings.json\n+++ b/homeassistant/components/swiss_public_transport/strings.json\n@@ -28,7 +28,7 @@\n           \"time_station\": \"Usually the departure time of a connection when it leaves the start station is tracked. Alternatively, track the time when the connection arrives at its end station.\",\n           \"time_mode\": \"Time mode lets you change the departure timing and fix it to a specific time (e.g. 7:12:00 AM every morning) or add a moving offset (e.g. +00:05:00 taking into account the time to walk to the station).\"\n         },\n-        \"description\": \"Provide start and end station for your connection,\\nand optionally up to 5 via stations.\\n\\nCheck the [stationboard]({stationboard_url}) for valid stations.\",\n+        \"description\": \"Provide start and end station for your connection,\\nand optionally up to 5 via stations.\\n\\nConsult the stationboard linked above.\",\n         \"title\": \"Swiss Public Transport\"\n       },\n       \"time_fixed\": {\n", "test_patch": "", "problem_statement": "Swiss Public Transport: Stationboard URL in error message not clickable\n### The problem\n\nWhen you provide some invalid station names in Swiss Public Transport this error banner comes up:\n\n![Image](https://github.com/user-attachments/assets/5e43c862-5850-453f-952b-4efeeb0d6051)\n\n\"Stationboard\" is supposed to be a clickable link here just like in the description right above it, but here the markup is rendered as plain text instead.\n\nThe simplest fix here might be to simply write \"Check at stationboard above \u2026\" instead as the link is already there.\n\n### What version of Home Assistant Core has the issue?\n\ncore-2025.2.0b2\n\n### What was the last working version of Home Assistant Core?\n\n_No response_\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nSwiss Public Transport\n\n### Link to integration documentation on our website\n\nhttps://www.home-assistant.io/integrations/swiss_public_transport\n\n### Diagnostics information\n\n_No response_\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\nSwiss Public Transport: Stationboard URL in error message not clickable\n### The problem\n\nWhen you provide some invalid station names in Swiss Public Transport this error banner comes up:\n\n![Image](https://github.com/user-attachments/assets/5e43c862-5850-453f-952b-4efeeb0d6051)\n\n\"Stationboard\" is supposed to be a clickable link here just like in the description right above it, but here the markup is rendered as plain text instead.\n\nThe simplest fix here might be to simply write \"Check at stationboard above \u2026\" instead as the link is already there.\n\n### What version of Home Assistant Core has the issue?\n\ncore-2025.2.0b2\n\n### What was the last working version of Home Assistant Core?\n\n_No response_\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nSwiss Public Transport\n\n### Link to integration documentation on our website\n\nhttps://www.home-assistant.io/integrations/swiss_public_transport\n\n### Diagnostics information\n\n_No response_\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\n", "hints_text": "\nHey there @fabaff, @miaucl, mind taking a look at this issue as it has been labeled with an integration (`swiss_public_transport`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1471) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `swiss_public_transport` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign swiss_public_transport` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[swiss_public_transport documentation](https://www.home-assistant.io/integrations/swiss_public_transport)\n[swiss_public_transport source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/swiss_public_transport)\n<sub><sup>(message by IssueLinks)</sup></sub>\n\nHey there @fabaff, @miaucl, mind taking a look at this issue as it has been labeled with an integration (`swiss_public_transport`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1471) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `swiss_public_transport` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign swiss_public_transport` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[swiss_public_transport documentation](https://www.home-assistant.io/integrations/swiss_public_transport)\n[swiss_public_transport source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/swiss_public_transport)\n<sub><sup>(message by IssueLinks)</sup></sub>", "created_at": "2025-01-31T12:06:46Z"}
{"repo": "home-assistant/core", "pull_number": 136982, "instance_id": "home-assistant__core-136982", "issue_numbers": ["136978", "136978"], "base_commit": "fc979cd564ee2d5fd27e05b32fa6f11b343ee4d5", "patch": "diff --git a/homeassistant/components/swiss_public_transport/icons.json b/homeassistant/components/swiss_public_transport/icons.json\nindex 06a640a06b2705..45cf4713705e63 100644\n--- a/homeassistant/components/swiss_public_transport/icons.json\n+++ b/homeassistant/components/swiss_public_transport/icons.json\n@@ -10,7 +10,7 @@\n       \"departure2\": {\n         \"default\": \"mdi:bus-clock\"\n       },\n-      \"duration\": {\n+      \"trip_duration\": {\n         \"default\": \"mdi:timeline-clock\"\n       },\n       \"transfers\": {\ndiff --git a/homeassistant/components/swiss_public_transport/sensor.py b/homeassistant/components/swiss_public_transport/sensor.py\nindex a0131938a37f9f..c8075a6746cbab 100644\n--- a/homeassistant/components/swiss_public_transport/sensor.py\n+++ b/homeassistant/components/swiss_public_transport/sensor.py\n@@ -56,8 +56,10 @@ class SwissPublicTransportSensorEntityDescription(SensorEntityDescription):\n     ],\n     SwissPublicTransportSensorEntityDescription(\n         key=\"duration\",\n+        translation_key=\"trip_duration\",\n         device_class=SensorDeviceClass.DURATION,\n         native_unit_of_measurement=UnitOfTime.SECONDS,\n+        suggested_unit_of_measurement=UnitOfTime.HOURS,\n         value_fn=lambda data_connection: data_connection[\"duration\"],\n     ),\n     SwissPublicTransportSensorEntityDescription(\ndiff --git a/homeassistant/components/swiss_public_transport/strings.json b/homeassistant/components/swiss_public_transport/strings.json\nindex ef8cc5595e3eff..270cb097e0a3a6 100644\n--- a/homeassistant/components/swiss_public_transport/strings.json\n+++ b/homeassistant/components/swiss_public_transport/strings.json\n@@ -64,8 +64,8 @@\n       \"departure2\": {\n         \"name\": \"Departure +2\"\n       },\n-      \"duration\": {\n-        \"name\": \"Duration\"\n+      \"trip_duration\": {\n+        \"name\": \"Trip duration\"\n       },\n       \"transfers\": {\n         \"name\": \"Transfers\"\n", "test_patch": "diff --git a/tests/components/swiss_public_transport/snapshots/test_sensor.ambr b/tests/components/swiss_public_transport/snapshots/test_sensor.ambr\nindex dbd689fc8f6ce3..b8ad82c7b79951 100644\n--- a/tests/components/swiss_public_transport/snapshots/test_sensor.ambr\n+++ b/tests/components/swiss_public_transport/snapshots/test_sensor.ambr\n@@ -192,7 +192,7 @@\n     'state': '2024-01-06T17:05:00+00:00',\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_duration-entry]\n+# name: test_all_entities[sensor.zurich_bern_line-entry]\n   EntityRegistryEntrySnapshot({\n     'aliases': set({\n     }),\n@@ -204,7 +204,7 @@\n     'disabled_by': None,\n     'domain': 'sensor',\n     'entity_category': None,\n-    'entity_id': 'sensor.zurich_bern_duration',\n+    'entity_id': 'sensor.zurich_bern_line',\n     'has_entity_name': True,\n     'hidden_by': None,\n     'icon': None,\n@@ -214,34 +214,32 @@\n     'name': None,\n     'options': dict({\n     }),\n-    'original_device_class': <SensorDeviceClass.DURATION: 'duration'>,\n+    'original_device_class': None,\n     'original_icon': None,\n-    'original_name': 'Duration',\n+    'original_name': 'Line',\n     'platform': 'swiss_public_transport',\n     'previous_unique_id': None,\n     'supported_features': 0,\n-    'translation_key': None,\n-    'unique_id': 'Z\u00fcrich Bern_duration',\n-    'unit_of_measurement': <UnitOfTime.SECONDS: 's'>,\n+    'translation_key': 'line',\n+    'unique_id': 'Z\u00fcrich Bern_line',\n+    'unit_of_measurement': None,\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_duration-state]\n+# name: test_all_entities[sensor.zurich_bern_line-state]\n   StateSnapshot({\n     'attributes': ReadOnlyDict({\n       'attribution': 'Data provided by transport.opendata.ch',\n-      'device_class': 'duration',\n-      'friendly_name': 'Z\u00fcrich Bern Duration',\n-      'unit_of_measurement': <UnitOfTime.SECONDS: 's'>,\n+      'friendly_name': 'Z\u00fcrich Bern Line',\n     }),\n     'context': <ANY>,\n-    'entity_id': 'sensor.zurich_bern_duration',\n+    'entity_id': 'sensor.zurich_bern_line',\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': '10',\n+    'state': 'T10',\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_line-entry]\n+# name: test_all_entities[sensor.zurich_bern_platform-entry]\n   EntityRegistryEntrySnapshot({\n     'aliases': set({\n     }),\n@@ -253,7 +251,7 @@\n     'disabled_by': None,\n     'domain': 'sensor',\n     'entity_category': None,\n-    'entity_id': 'sensor.zurich_bern_line',\n+    'entity_id': 'sensor.zurich_bern_platform',\n     'has_entity_name': True,\n     'hidden_by': None,\n     'icon': None,\n@@ -265,30 +263,30 @@\n     }),\n     'original_device_class': None,\n     'original_icon': None,\n-    'original_name': 'Line',\n+    'original_name': 'Platform',\n     'platform': 'swiss_public_transport',\n     'previous_unique_id': None,\n     'supported_features': 0,\n-    'translation_key': 'line',\n-    'unique_id': 'Z\u00fcrich Bern_line',\n+    'translation_key': 'platform',\n+    'unique_id': 'Z\u00fcrich Bern_platform',\n     'unit_of_measurement': None,\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_line-state]\n+# name: test_all_entities[sensor.zurich_bern_platform-state]\n   StateSnapshot({\n     'attributes': ReadOnlyDict({\n       'attribution': 'Data provided by transport.opendata.ch',\n-      'friendly_name': 'Z\u00fcrich Bern Line',\n+      'friendly_name': 'Z\u00fcrich Bern Platform',\n     }),\n     'context': <ANY>,\n-    'entity_id': 'sensor.zurich_bern_line',\n+    'entity_id': 'sensor.zurich_bern_platform',\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': 'T10',\n+    'state': '0',\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_platform-entry]\n+# name: test_all_entities[sensor.zurich_bern_transfers-entry]\n   EntityRegistryEntrySnapshot({\n     'aliases': set({\n     }),\n@@ -300,7 +298,7 @@\n     'disabled_by': None,\n     'domain': 'sensor',\n     'entity_category': None,\n-    'entity_id': 'sensor.zurich_bern_platform',\n+    'entity_id': 'sensor.zurich_bern_transfers',\n     'has_entity_name': True,\n     'hidden_by': None,\n     'icon': None,\n@@ -312,30 +310,30 @@\n     }),\n     'original_device_class': None,\n     'original_icon': None,\n-    'original_name': 'Platform',\n+    'original_name': 'Transfers',\n     'platform': 'swiss_public_transport',\n     'previous_unique_id': None,\n     'supported_features': 0,\n-    'translation_key': 'platform',\n-    'unique_id': 'Z\u00fcrich Bern_platform',\n+    'translation_key': 'transfers',\n+    'unique_id': 'Z\u00fcrich Bern_transfers',\n     'unit_of_measurement': None,\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_platform-state]\n+# name: test_all_entities[sensor.zurich_bern_transfers-state]\n   StateSnapshot({\n     'attributes': ReadOnlyDict({\n       'attribution': 'Data provided by transport.opendata.ch',\n-      'friendly_name': 'Z\u00fcrich Bern Platform',\n+      'friendly_name': 'Z\u00fcrich Bern Transfers',\n     }),\n     'context': <ANY>,\n-    'entity_id': 'sensor.zurich_bern_platform',\n+    'entity_id': 'sensor.zurich_bern_transfers',\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n     'state': '0',\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_transfers-entry]\n+# name: test_all_entities[sensor.zurich_bern_trip_duration-entry]\n   EntityRegistryEntrySnapshot({\n     'aliases': set({\n     }),\n@@ -347,7 +345,7 @@\n     'disabled_by': None,\n     'domain': 'sensor',\n     'entity_category': None,\n-    'entity_id': 'sensor.zurich_bern_transfers',\n+    'entity_id': 'sensor.zurich_bern_trip_duration',\n     'has_entity_name': True,\n     'hidden_by': None,\n     'icon': None,\n@@ -356,29 +354,34 @@\n     }),\n     'name': None,\n     'options': dict({\n+      'sensor.private': dict({\n+        'suggested_unit_of_measurement': <UnitOfTime.HOURS: 'h'>,\n+      }),\n     }),\n-    'original_device_class': None,\n+    'original_device_class': <SensorDeviceClass.DURATION: 'duration'>,\n     'original_icon': None,\n-    'original_name': 'Transfers',\n+    'original_name': 'Trip duration',\n     'platform': 'swiss_public_transport',\n     'previous_unique_id': None,\n     'supported_features': 0,\n-    'translation_key': 'transfers',\n-    'unique_id': 'Z\u00fcrich Bern_transfers',\n-    'unit_of_measurement': None,\n+    'translation_key': 'trip_duration',\n+    'unique_id': 'Z\u00fcrich Bern_duration',\n+    'unit_of_measurement': <UnitOfTime.HOURS: 'h'>,\n   })\n # ---\n-# name: test_all_entities[sensor.zurich_bern_transfers-state]\n+# name: test_all_entities[sensor.zurich_bern_trip_duration-state]\n   StateSnapshot({\n     'attributes': ReadOnlyDict({\n       'attribution': 'Data provided by transport.opendata.ch',\n-      'friendly_name': 'Z\u00fcrich Bern Transfers',\n+      'device_class': 'duration',\n+      'friendly_name': 'Z\u00fcrich Bern Trip duration',\n+      'unit_of_measurement': <UnitOfTime.HOURS: 'h'>,\n     }),\n     'context': <ANY>,\n-    'entity_id': 'sensor.zurich_bern_transfers',\n+    'entity_id': 'sensor.zurich_bern_trip_duration',\n     'last_changed': <ANY>,\n     'last_reported': <ANY>,\n     'last_updated': <ANY>,\n-    'state': '0',\n+    'state': '0.003',\n   })\n # ---\ndiff --git a/tests/components/swiss_public_transport/test_sensor.py b/tests/components/swiss_public_transport/test_sensor.py\nindex 4afdd88c9de2f8..6e8327282773e7 100644\n--- a/tests/components/swiss_public_transport/test_sensor.py\n+++ b/tests/components/swiss_public_transport/test_sensor.py\n@@ -83,7 +83,7 @@ async def test_fetching_data(\n         hass.states.get(\"sensor.zurich_bern_departure_2\").state\n         == \"2024-01-06T17:05:00+00:00\"\n     )\n-    assert hass.states.get(\"sensor.zurich_bern_duration\").state == \"10\"\n+    assert hass.states.get(\"sensor.zurich_bern_trip_duration\").state == \"0.003\"\n     assert hass.states.get(\"sensor.zurich_bern_platform\").state == \"0\"\n     assert hass.states.get(\"sensor.zurich_bern_transfers\").state == \"0\"\n     assert hass.states.get(\"sensor.zurich_bern_delay\").state == \"0\"\n", "problem_statement": "Swiss Public Transport: Duration field uses generic name and seconds as default unit\n### The problem\n\nThe entity \"Duration\" has a translatable friendly name defined in the strings.json of the Swiss Public Transport integration:\n\nhttps://github.com/home-assistant/core/blob/fc979cd564ee2d5fd27e05b32fa6f11b343ee4d5/homeassistant/components/swiss_public_transport/strings.json#L67-L68\n\nBut that field does not seem to get used for that name but some generic \"Duration\" field instead. \n\nIn German I have translated this field as \"Fahrzeit\" in Lokalise\n\n![Image](https://github.com/user-attachments/assets/ff44215c-2550-4386-a39a-3681ac47c9a9)\n\nbut I still see \"Dauer\" in the UI:\n\n![Image](https://github.com/user-attachments/assets/9d3c3ca8-1a91-4490-8223-261ed8307709)\n\nAll other sensors have picked up their localized names as they should.\n\n\nIn addtion it would be cool if that field used hours as the unit by default.\nAs a user I can make this change in the entity settings and it's much more useful then:\n\n![Image](https://github.com/user-attachments/assets/8f9da90b-8032-4539-b724-b531c2feda12)\n\n### What version of Home Assistant Core has the issue?\n\ncore-2025.2.0b2\n\n### What was the last working version of Home Assistant Core?\n\n_No response_\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nSwiss Public Transport\n\n### Link to integration documentation on our website\n\nhttps://rc.home-assistant.io/integrations/swiss_public_transport\n\n### Diagnostics information\n\n_No response_\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\nSwiss Public Transport: Duration field uses generic name and seconds as default unit\n### The problem\n\nThe entity \"Duration\" has a translatable friendly name defined in the strings.json of the Swiss Public Transport integration:\n\nhttps://github.com/home-assistant/core/blob/fc979cd564ee2d5fd27e05b32fa6f11b343ee4d5/homeassistant/components/swiss_public_transport/strings.json#L67-L68\n\nBut that field does not seem to get used for that name but some generic \"Duration\" field instead. \n\nIn German I have translated this field as \"Fahrzeit\" in Lokalise\n\n![Image](https://github.com/user-attachments/assets/ff44215c-2550-4386-a39a-3681ac47c9a9)\n\nbut I still see \"Dauer\" in the UI:\n\n![Image](https://github.com/user-attachments/assets/9d3c3ca8-1a91-4490-8223-261ed8307709)\n\nAll other sensors have picked up their localized names as they should.\n\n\nIn addtion it would be cool if that field used hours as the unit by default.\nAs a user I can make this change in the entity settings and it's much more useful then:\n\n![Image](https://github.com/user-attachments/assets/8f9da90b-8032-4539-b724-b531c2feda12)\n\n### What version of Home Assistant Core has the issue?\n\ncore-2025.2.0b2\n\n### What was the last working version of Home Assistant Core?\n\n_No response_\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nSwiss Public Transport\n\n### Link to integration documentation on our website\n\nhttps://rc.home-assistant.io/integrations/swiss_public_transport\n\n### Diagnostics information\n\n_No response_\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\n", "hints_text": "\nHey there @fabaff, @miaucl, mind taking a look at this issue as it has been labeled with an integration (`swiss_public_transport`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1471) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `swiss_public_transport` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign swiss_public_transport` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[swiss_public_transport documentation](https://www.home-assistant.io/integrations/swiss_public_transport)\n[swiss_public_transport source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/swiss_public_transport)\n<sub><sup>(message by IssueLinks)</sup></sub>\n@NoRi2909 Good spot, the translation key was missing for `Duration`. But regarding the duration measurement unit, The raw data arriving is in seconds and I do not want to opinionate and convert in home assistant, this is usually up to the user.\n\nHey there @fabaff, @miaucl, mind taking a look at this issue as it has been labeled with an integration (`swiss_public_transport`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1471) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `swiss_public_transport` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign swiss_public_transport` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[swiss_public_transport documentation](https://www.home-assistant.io/integrations/swiss_public_transport)\n[swiss_public_transport source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/swiss_public_transport)\n<sub><sup>(message by IssueLinks)</sup></sub>\n@NoRi2909 Good spot, the translation key was missing for `Duration`. But regarding the duration measurement unit, The raw data arriving is in seconds and I do not want to opinionate and convert in home assistant, this is usually up to the user.", "created_at": "2025-01-31T09:07:10Z"}
{"repo": "home-assistant/core", "pull_number": 136980, "instance_id": "home-assistant__core-136980", "issue_numbers": ["136959"], "base_commit": "fc979cd564ee2d5fd27e05b32fa6f11b343ee4d5", "patch": "diff --git a/homeassistant/components/onedrive/backup.py b/homeassistant/components/onedrive/backup.py\nindex 94d60bc6398125..7f4bd5a07383cc 100644\n--- a/homeassistant/components/onedrive/backup.py\n+++ b/homeassistant/components/onedrive/backup.py\n@@ -2,6 +2,7 @@\n \n from __future__ import annotations\n \n+import asyncio\n from collections.abc import AsyncIterator, Callable, Coroutine\n from functools import wraps\n import html\n@@ -9,7 +10,7 @@\n import logging\n from typing import Any, Concatenate, cast\n \n-from httpx import Response\n+from httpx import Response, TimeoutException\n from kiota_abstractions.api_error import APIError\n from kiota_abstractions.authentication import AnonymousAuthenticationProvider\n from kiota_abstractions.headers_collection import HeadersCollection\n@@ -42,6 +43,7 @@\n \n _LOGGER = logging.getLogger(__name__)\n UPLOAD_CHUNK_SIZE = 16 * 320 * 1024  # 5.2MB\n+MAX_RETRIES = 5\n \n \n async def async_get_backup_agents(\n@@ -96,7 +98,7 @@ async def wrapper(\n             )\n             _LOGGER.debug(\"Full error: %s\", err, exc_info=True)\n             raise BackupAgentError(\"Backup operation failed\") from err\n-        except TimeoutError as err:\n+        except TimeoutException as err:\n             _LOGGER.error(\n                 \"Error during backup in %s: Timeout\",\n                 func.__name__,\n@@ -268,6 +270,7 @@ async def async_upload(\n         start = 0\n         buffer: list[bytes] = []\n         buffer_size = 0\n+        retries = 0\n \n         async for chunk in stream:\n             buffer.append(chunk)\n@@ -279,11 +282,28 @@ async def async_upload(\n                     buffer_size > UPLOAD_CHUNK_SIZE\n                 ):  # Loop in case the buffer is >= UPLOAD_CHUNK_SIZE * 2\n                     slice_start = uploaded_chunks * UPLOAD_CHUNK_SIZE\n-                    await async_upload(\n-                        start,\n-                        start + UPLOAD_CHUNK_SIZE - 1,\n-                        chunk_data[slice_start : slice_start + UPLOAD_CHUNK_SIZE],\n-                    )\n+                    try:\n+                        await async_upload(\n+                            start,\n+                            start + UPLOAD_CHUNK_SIZE - 1,\n+                            chunk_data[slice_start : slice_start + UPLOAD_CHUNK_SIZE],\n+                        )\n+                    except APIError as err:\n+                        if (\n+                            err.response_status_code and err.response_status_code < 500\n+                        ):  # no retry on 4xx errors\n+                            raise\n+                        if retries < MAX_RETRIES:\n+                            await asyncio.sleep(2**retries)\n+                            retries += 1\n+                            continue\n+                        raise\n+                    except TimeoutException:\n+                        if retries < MAX_RETRIES:\n+                            retries += 1\n+                            continue\n+                        raise\n+                    retries = 0\n                     start += UPLOAD_CHUNK_SIZE\n                     uploaded_chunks += 1\n                     buffer_size -= UPLOAD_CHUNK_SIZE\n", "test_patch": "diff --git a/tests/components/onedrive/conftest.py b/tests/components/onedrive/conftest.py\nindex 65142217017431..649966a7828978 100644\n--- a/tests/components/onedrive/conftest.py\n+++ b/tests/components/onedrive/conftest.py\n@@ -176,3 +176,10 @@ def mock_instance_id() -> Generator[AsyncMock]:\n         return_value=\"9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0\",\n     ):\n         yield\n+\n+\n+@pytest.fixture(autouse=True)\n+def mock_asyncio_sleep() -> Generator[AsyncMock]:\n+    \"\"\"Mock asyncio.sleep.\"\"\"\n+    with patch(\"homeassistant.components.onedrive.backup.asyncio.sleep\", AsyncMock()):\n+        yield\ndiff --git a/tests/components/onedrive/test_backup.py b/tests/components/onedrive/test_backup.py\nindex 3492202d3feb08..162ecb7d92ae74 100644\n--- a/tests/components/onedrive/test_backup.py\n+++ b/tests/components/onedrive/test_backup.py\n@@ -8,8 +8,10 @@\n from json import dumps\n from unittest.mock import Mock, patch\n \n+from httpx import TimeoutException\n from kiota_abstractions.api_error import APIError\n from msgraph.generated.models.drive_item import DriveItem\n+from msgraph_core.models import LargeFileUploadSession\n import pytest\n \n from homeassistant.components.backup import DOMAIN as BACKUP_DOMAIN, AgentBackup\n@@ -255,6 +257,140 @@ async def test_broken_upload_session(\n     assert \"Failed to start backup upload\" in caplog.text\n \n \n+@pytest.mark.parametrize(\n+    \"side_effect\",\n+    [\n+        APIError(response_status_code=500),\n+        TimeoutException(\"Timeout\"),\n+    ],\n+)\n+async def test_agents_upload_errors_retried(\n+    hass_client: ClientSessionGenerator,\n+    caplog: pytest.LogCaptureFixture,\n+    mock_drive_items: MagicMock,\n+    mock_config_entry: MockConfigEntry,\n+    mock_adapter: MagicMock,\n+    side_effect: Exception,\n+) -> None:\n+    \"\"\"Test agent upload backup.\"\"\"\n+    client = await hass_client()\n+    test_backup = AgentBackup.from_dict(BACKUP_METADATA)\n+\n+    mock_adapter.send_async.side_effect = [\n+        side_effect,\n+        LargeFileUploadSession(next_expected_ranges=[\"2-\"]),\n+        LargeFileUploadSession(next_expected_ranges=[\"2-\"]),\n+    ]\n+\n+    with (\n+        patch(\n+            \"homeassistant.components.backup.manager.BackupManager.async_get_backup\",\n+        ) as fetch_backup,\n+        patch(\n+            \"homeassistant.components.backup.manager.read_backup\",\n+            return_value=test_backup,\n+        ),\n+        patch(\"pathlib.Path.open\") as mocked_open,\n+        patch(\"homeassistant.components.onedrive.backup.UPLOAD_CHUNK_SIZE\", 3),\n+    ):\n+        mocked_open.return_value.read = Mock(side_effect=[b\"test\", b\"\"])\n+        fetch_backup.return_value = test_backup\n+        resp = await client.post(\n+            f\"/api/backup/upload?agent_id={DOMAIN}.{mock_config_entry.unique_id}\",\n+            data={\"file\": StringIO(\"test\")},\n+        )\n+\n+    assert resp.status == 201\n+    assert mock_adapter.send_async.call_count == 3\n+    assert f\"Uploading backup {test_backup.backup_id}\" in caplog.text\n+    mock_drive_items.patch.assert_called_once()\n+\n+\n+async def test_agents_upload_4xx_errors_not_retried(\n+    hass_client: ClientSessionGenerator,\n+    caplog: pytest.LogCaptureFixture,\n+    mock_drive_items: MagicMock,\n+    mock_config_entry: MockConfigEntry,\n+    mock_adapter: MagicMock,\n+) -> None:\n+    \"\"\"Test agent upload backup.\"\"\"\n+    client = await hass_client()\n+    test_backup = AgentBackup.from_dict(BACKUP_METADATA)\n+\n+    mock_adapter.send_async.side_effect = APIError(response_status_code=404)\n+\n+    with (\n+        patch(\n+            \"homeassistant.components.backup.manager.BackupManager.async_get_backup\",\n+        ) as fetch_backup,\n+        patch(\n+            \"homeassistant.components.backup.manager.read_backup\",\n+            return_value=test_backup,\n+        ),\n+        patch(\"pathlib.Path.open\") as mocked_open,\n+        patch(\"homeassistant.components.onedrive.backup.UPLOAD_CHUNK_SIZE\", 3),\n+    ):\n+        mocked_open.return_value.read = Mock(side_effect=[b\"test\", b\"\"])\n+        fetch_backup.return_value = test_backup\n+        resp = await client.post(\n+            f\"/api/backup/upload?agent_id={DOMAIN}.{mock_config_entry.unique_id}\",\n+            data={\"file\": StringIO(\"test\")},\n+        )\n+\n+    assert resp.status == 201\n+    assert mock_adapter.send_async.call_count == 1\n+    assert f\"Uploading backup {test_backup.backup_id}\" in caplog.text\n+    assert mock_drive_items.patch.call_count == 0\n+    assert \"Backup operation failed\" in caplog.text\n+\n+\n+@pytest.mark.parametrize(\n+    (\"side_effect\", \"error\"),\n+    [\n+        (APIError(response_status_code=500), \"Backup operation failed\"),\n+        (TimeoutException(\"Timeout\"), \"Backup operation timed out\"),\n+    ],\n+)\n+async def test_agents_upload_fails_after_max_retries(\n+    hass_client: ClientSessionGenerator,\n+    caplog: pytest.LogCaptureFixture,\n+    mock_drive_items: MagicMock,\n+    mock_config_entry: MockConfigEntry,\n+    mock_adapter: MagicMock,\n+    side_effect: Exception,\n+    error: str,\n+) -> None:\n+    \"\"\"Test agent upload backup.\"\"\"\n+    client = await hass_client()\n+    test_backup = AgentBackup.from_dict(BACKUP_METADATA)\n+\n+    mock_adapter.send_async.side_effect = side_effect\n+\n+    with (\n+        patch(\n+            \"homeassistant.components.backup.manager.BackupManager.async_get_backup\",\n+        ) as fetch_backup,\n+        patch(\n+            \"homeassistant.components.backup.manager.read_backup\",\n+            return_value=test_backup,\n+        ),\n+        patch(\"pathlib.Path.open\") as mocked_open,\n+        patch(\"homeassistant.components.onedrive.backup.UPLOAD_CHUNK_SIZE\", 3),\n+    ):\n+        mocked_open.return_value.read = Mock(side_effect=[b\"test\", b\"\"])\n+        fetch_backup.return_value = test_backup\n+        resp = await client.post(\n+            f\"/api/backup/upload?agent_id={DOMAIN}.{mock_config_entry.unique_id}\",\n+            data={\"file\": StringIO(\"test\")},\n+        )\n+\n+    assert resp.status == 201\n+    assert mock_adapter.send_async.call_count == 6\n+    assert f\"Uploading backup {test_backup.backup_id}\" in caplog.text\n+    assert mock_drive_items.patch.call_count == 0\n+    assert error in caplog.text\n+\n+\n async def test_agents_download(\n     hass_client: ClientSessionGenerator,\n     mock_drive_items: MagicMock,\n@@ -282,7 +418,7 @@ async def test_agents_download(\n             APIError(response_status_code=500),\n             \"Backup operation failed\",\n         ),\n-        (TimeoutError(), \"Backup operation timed out\"),\n+        (TimeoutException(\"Timeout\"), \"Backup operation timed out\"),\n     ],\n )\n async def test_delete_error(\n", "problem_statement": "2025.2.0b2 One Drive Automatic backup fails\n### The problem\n\nInitiated an automatic backup One Drive failed.  Local, local network and Google Drive succeeded \nRepeated 10 minutes later same failure. I'm able to access One Drive directly on my PC  \n\n![Image](https://github.com/user-attachments/assets/2e9ccd95-ded7-4f8b-b10d-ba14c2032184)\n\n### What version of Home Assistant Core has the issue?\n\n2025.2.0b2\n\n### What was the last working version of Home Assistant Core?\n\n2025.2.0b1\n\n### What type of installation are you running?\n\nHome Assistant OS\n\n### Integration causing the issue\n\nBackup\n\n### Link to integration documentation on our website\n\n_No response_\n\n### Diagnostics information\n\n```\nLogger: homeassistant.components.backup\nSource: components/backup/manager.py:512\nintegration: Backup ([documentation](https://rc.home-assistant.io/integrations/backup), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+backup%22))\nFirst occurred: 2:32:18 PM (1 occurrences)\nLast logged: 2:32:18 PM\n\nUnexpected error for onedrive.D378A3F5743D8717:\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py\", line 101, in map_httpcore_exceptions\n    yield\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py\", line 394, in handle_async_request\n    resp = await self._pool.handle_async_request(req)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py\", line 256, in handle_async_request\n    raise exc from None\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py\", line 236, in handle_async_request\n    response = await connection.handle_async_request(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        pool_request.request\n        ^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/connection.py\", line 103, in handle_async_request\n    return await self._connection.handle_async_request(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py\", line 136, in handle_async_request\n    raise exc\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py\", line 106, in handle_async_request\n    ) = await self._receive_response_headers(**kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py\", line 177, in _receive_response_headers\n    event = await self._receive_event(timeout=timeout)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_async/http11.py\", line 217, in _receive_event\n    data = await self._network_stream.read(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        self.READ_NUM_BYTES, timeout=timeout\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_backends/anyio.py\", line 32, in read\n    with map_exceptions(exc_map):\n         ~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/usr/local/lib/python3.13/contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n    raise to_exc(exc) from exc\nhttpcore.ReadTimeout\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/src/homeassistant/homeassistant/components/backup/manager.py\", line 512, in upload_backup_to_agent\n    await self.backup_agents[agent_id].async_upload_backup(\n    ...<2 lines>...\n    )\n  File \"/usr/src/homeassistant/homeassistant/components/onedrive/backup.py\", line 87, in wrapper\n    return await func(self, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/src/homeassistant/homeassistant/components/onedrive/backup.py\", line 172, in async_upload_backup\n    await self._upload_file(\n        upload_session.upload_url, await open_stream(), backup.size\n    )\n  File \"/usr/src/homeassistant/homeassistant/components/onedrive/backup.py\", line 282, in _upload_file\n    await async_upload(\n    ...<3 lines>...\n    )\n  File \"/usr/src/homeassistant/homeassistant/components/onedrive/backup.py\", line 264, in async_upload\n    result = await adapter.send_async(info, LargeFileUploadSession, {})\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/kiota_http/httpx_request_adapter.py\", line 186, in send_async\n    response = await self.get_http_response_message(request_info, parent_span)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/kiota_http/httpx_request_adapter.py\", line 602, in get_http_response_message\n    resp = await self._http_client.send(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_client.py\", line 1629, in send\n    response = await self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<4 lines>...\n    )\n    ^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_client.py\", line 1657, in _send_handling_auth\n    response = await self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_client.py\", line 1694, in _send_handling_redirects\n    response = await self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_client.py\", line 1730, in _send_single_request\n    response = await transport.handle_async_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py\", line 393, in handle_async_request\n    with map_httpcore_exceptions():\n         ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/usr/local/lib/python3.13/contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py\", line 118, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\nhttpx.ReadTimeout\n```\n\n\n### Example YAML snippet\n\n```yaml\n\n```\n\n### Anything in the logs that might be useful for us?\n\n```txt\n\n```\n\n### Additional information\n\n_No response_\n", "hints_text": "\nHey there @home-assistant/core, mind taking a look at this issue as it has been labeled with an integration (`backup`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L183) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `backup` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign backup` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[backup documentation](https://www.home-assistant.io/integrations/backup)\n[backup source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/backup)\n<sub><sup>(message by IssueLinks)</sup></sub>\nJust want to chime in that I get the same error. With 2025.2.0b1 I could not connect to OneDrive. With b2 it is possible to link it.\n\n```\nLogger: homeassistant.components.onedrive.backup\nSource: components/onedrive/backup.py:91\nintegration: OneDrive (documentation, issues)\nFirst occurred: 22:08:57 (1 occurrences)\nLast logged: 22:08:57\n\nError during backup in async_upload_backup: Status 400, message None\n```\n\nAnd\n```\nLogger: homeassistant.components.backup\nSource: components/backup/manager.py:531\nintegration: Backup (documentation, issues)\nFirst occurred: 22:08:57 (1 occurrences)\nLast logged: 22:08:57\n\nUpload failed for onedrive.ea093e654287a17c: Backup operation failed\n```\n\nHmm, just checked my OneDrive and the Folders /Apps/Home Assistant/backups_slug/ are created and I even see a .tar file in the folder.\n\nThe state inside Home Assistant still says the upload failed though.\n\nTried an encrypted and unencrypted OneDrive backup. Both give the same error, and both upload the file just fine.\nJust tried the same thing again; Initiated an automated backup and the upload to One Drive succeeded. \nAppears to be an intermittent problem\n\nHey there @zweckj, mind taking a look at this issue as it has been labeled with an integration (`onedrive`) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L1076) for? Thanks!\n\n<details>\n<summary>Code owner commands</summary>\n\n\nCode owners of `onedrive` can trigger bot actions by commenting:\n\n- `@home-assistant close` Closes the issue.\n- `@home-assistant rename Awesome new title` Renames the issue.\n- `@home-assistant reopen` Reopen the issue.\n- `@home-assistant unassign onedrive` Removes the current integration label and assignees on the issue, add the integration domain after the command.\n- `@home-assistant add-label needs-more-information` Add a label (needs-more-information, problem in dependency, problem in custom component) to the issue.\n- `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information, problem in dependency, problem in custom component) on the issue.\n\n</details>\n\n\n<sub><sup>(message by CodeOwnersMention)</sup></sub>\n\n---\n\n[onedrive documentation](https://www.home-assistant.io/integrations/onedrive)\n[onedrive source](https://github.com/home-assistant/core/tree/dev/homeassistant/components/onedrive)\n<sub><sup>(message by IssueLinks)</sup></sub>", "created_at": "2025-01-31T08:31:24Z"}
